name: Codiga C++ CQC

on:
  push:
    paths:
      - '**.cpp'
      - '!**-og**'

jobs:
  qc:
    runs-on: ubuntu-latest
    name: Codiga
    
    steps:
    - name: Code Quality Check
      id: codiga
      uses: codiga/github-action@master
      continue-on-error: true
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
        force_ref: 'none'
        min_quality_grade: 'WARNING'
        min_quality_score: '80'
        max_defects_rate: '0.001'
        max_complex_functions_rate: '0.7'
        max_long_functions_rate: '0.7'
        project_name: 'University'
        max_timeout_sec: '300'
    
    
    - name: ↧ Checkout
      id: co
      if: steps.codiga.outcome == 'failure'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
      
    - name: 💬 Get commit message
      id: gc
      if: steps.co.outcome == 'success'
      uses: rlespinasse/git-commit-data-action@v1
    
    - name: 🗒 Get commit message history
      id: cmsg
      if: steps.gc.outcome == 'success'
      run: git log > cmsg.txt
    
    - name: ✏ Prepare issue body (regex)
      id: issue-body
      if: steps.cmsg.outcome == 'success'
      run: head -5 cmsg.txt > issue.txt
          
    - name: ✍ Create new issue
      id: issuer
      if: steps.issue-body.outcome == 'success'
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: "Codiga C++: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} | ${{ env.GIT_COMMIT_SHORT_SHA }}"
        content-filepath: issue.txt
        labels: lint
        
    - name: ⛔ Code not met quality criteria
      if: steps.issuer.outcome == 'success'
      run: exit 1