name: Submission CM Verifier

on:
  push:
    paths:
      - 'CS102/**'
      - 'CS104/exc/L/**'
      - 'CS104/exc/T/**'
      - '.github/**'

jobs:
  check-cmsg:
    name: Check commit message
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: ↧ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: 💬 Get commit message
        uses: rlespinasse/git-commit-data-action@v1
        
      - name: 🗒 Get commit message history
        id: cmsg-history
        run: git log > cmsg.txt
        
        
        # Pattern explanation:
        #               (1)             |                 (2)                     |          (3)
        # ------------------------------+-----------------------------------------+------------------------
        #      req. if (3) is missing   |               required                  | only if (1) is missing
        # ------------------------------+-----------------------------------------+------------------------
        #     [|3 characters|]|*space*  |  3 digits|*dot*|L or T|*dot*|2 digits   |    |*dot*|2 digits|
        #
        #   Match:
        #     - 104.L.02.01
        #     - [add] 104.T.05
        #     - [rnm] 104.T.05 > 104.T.06.31
        #
        #   Won't match:
        #     - 104.T.03
        #     - [xyz] 104.T.05
        #     - [rnm] 104.T.05
        #     - [mod] 104.L.02.02
        #     - 104.l.02.01
        #     - 104.X.02.03
        #     - [delete] 42069.LT.2.112
        
      - name: 🔎 Regex check 1
        id: regex-1
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '([0-9]{3}\.[LT]\.[0-9]{2}\.[0-9]{2}(?<!^\[(add|del|rnm|mov|rft)\]\ ))'
          regex_flags: 'gm'
          search_string: '${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}'
          
      - name: 🔎 Regex check 2
        id: regex-2
        if: steps.regex-1.outputs.first_match == ''
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '(\[(add|del|mov|rft)\]\ (?=[0-9]{3}\.[LT]\.[0-9]{2}$))'
          regex_flags: 'gm'
          search_string: '${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}'
          
      - name: 🔎 Regex check 3
        id: regex-3
        if: steps.regex-2.outputs.first_match == ''
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '(\[rnm\]\ (?=.*\>.*))'
          regex_flags: 'gm'
          search_string: '${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}'
          
      - name: ✏ Prepare issue body (regex)
        id: issue-body-reg
        if: steps.regex-1.outputs.first_match == '' && steps.regex-2.outputs.first_match == '' && steps.regex-3.outputs.first_match == ''
        run: head -5 cmsg.txt > issue.txt
          
      - name: ✍ Create new issue (regex)
        id: issuer-reg
        if: steps.issue-body-reg.outcome == 'success'
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "CCMV - Regex: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} (${{ env.GIT_COMMIT_SHORT_SHA }})"
          content-filepath: issue.txt
          labels: cm-reg
          
      - name: ⛔ Failed regex check
        if: steps.issuer-reg.outcome == 'success'
        run: exit 1
        
          
      - name: 👓 Search through cmsg.txt
        id: search
        continue-on-error: true
        run: |
          msg=$(cat cmsg.txt)
          count=+
          for line in $msg
          do
            if [[ "$line" =~ "${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}" ]]
            then
              count=$count+
              
              if [[ "$count" = "+++" ]]
              then
                exit 1
              fi
            fi
          done
          
      - name: ✏ Prepare issue body (duplication)
        id: issue-body-dup
        if: steps.search.outcome == 'failure'
        run: head -5 cmsg.txt > issue.txt
          
      - name: ✍ Create new issue (duplication)
        id: issuer-dup
        if: steps.issue-body-dup.outcome == 'success'
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "CCMV - Duplication: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} (${{ env.GIT_COMMIT_SHORT_SHA }})"
          content-filepath: issue.txt
          labels: cm-dup
          
      - name: ⛔ Found Duplicate
        if: steps.issuer-dup.outcome == 'success'
        run: exit 1